# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

# Controls when the action will run. Triggers the workflow on schedule
# events but only for the master branch
on:
  schedule:
  - cron: "3 * * * 1-5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven max-workspace
      run: mvn -B install --file bnd-maven/max-workspace/pom.xml
    - uses: actions/checkout@v2
    - name: git add
      run: |
           date +%s > report.txt
           touch new_file
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        commit-message: Generate reports with latest bnd-version 
        title: Generate reports with latest bnd-version
        body: |
             Updates 
             
             Auto-generated by Action
            
        labels: generated-readme, automated pr
        branch: master
